import { CreatorProfile, PortfolioItem, BrandProfile, CreativeBrief } from "./types";

export type DemoCreatorWithPortfolio = {
  creator: CreatorProfile;
  portfolio: PortfolioItem[];
};

export const DEMO_CREATORS: DemoCreatorWithPortfolio[] = [
  {
    creator: {
      name: "Maya Verma",
      username: "mayaverma",
      email: "maya@krealink.ai",
      specialization: "AI Commercial Director & VFX Lead",
      bio: "Award-winning commercial filmmaker specializing in high-speed kinetic camera work, photorealistic AI character consistency, and branded product motion.",
      availability: "Available immediately",
      commercialUse: true,
      skills: [
        "Prompt Engineering",
        "Character Consistency",
        "Camera Movement Control",
        "Motion Tracking & VFX",
        "Storyboarding & Animatics",
        "Post-Processing & Upscaling",
        "Color Grading & Finishing",
      ],
      aiTools: ["Runway", "Kling AI", "Midjourney", "ComfyUI", "Topaz Video AI", "DaVinci Resolve"],
      aiModels: ["Runway Gen-3 Alpha", "Kling 1.5", "Flux.1 Dev", "Midjourney v6.1"],
      contentTypes: [
        "Brand Commercials",
        "Short-form Video (Reels/TikTok)",
        "Cinematic Trailers",
        "Social Media Ads",
      ],
      formats: [
        "9:16 Vertical (Reels/Shorts)",
        "16:9 Landscape (YouTube/TV)",
        "4K UHD",
        "1080p Full HD",
      ],
      workflow:
        "Concept development & keyframe consistency in Midjourney v6.1 & Flux, high-dynamic motion synthesis with Runway Gen-3 & Kling 1.5, 4K temporal stabilization in Topaz Video AI, and finishing in DaVinci Resolve Studio.",
      profilePhoto: "",
      socialLinks: {
        website: "https://mayaverma.ai",
        x: "https://x.com/mayaverma_ai",
        instagram: "https://instagram.com/mayaverma.ai",
      },
      verified: true,
      verification: {
        tools: true,
        workflow: true,
        portfolio: true,
      },
      status: "Active",
      theme: "flame",
    },
    portfolio: [
      {
        id: "maya-p1",
        title: "Velocity-X Sneaker Teaser",
        description: "Kinetic 30s product spot for a futuristic performance running shoe with neon particle trails.",
        mediaUrl: "/reels/reel-01.mp4",
        thumbnailUrl: "/reels/reel-01.jpg",
        contentType: "Short-form Video (Reels/TikTok)",
        tools: ["Runway", "Midjourney", "Topaz Video AI"],
        models: ["Runway Gen-3 Alpha", "Midjourney v6.1"],
        skills: ["Camera Movement Control", "Character Consistency", "Motion Tracking & VFX"],
        workflow: "Midjourney concept → Runway camera zoom → Topaz 4K upscale",
        formats: ["9:16 Vertical (Reels/Shorts)", "4K UHD"],
        commercialUse: true,
      },
      {
        id: "maya-p2",
        title: "Aura Hyper-Drink Campaign",
        description: "Vibrant liquid dynamics and fluid simulations for high-energy Gen-Z beverage launch.",
        mediaUrl: "/reels/reel-02.mp4",
        thumbnailUrl: "/reels/reel-02.jpg",
        contentType: "Brand Commercials",
        tools: ["Kling AI", "ComfyUI", "DaVinci Resolve"],
        models: ["Kling 1.5", "Flux.1 Dev"],
        skills: ["Prompt Engineering", "Color Grading & Finishing"],
        workflow: "ComfyUI ControlNet → Kling 1.5 video synthesis → DaVinci color grading",
        formats: ["9:16 Vertical (Reels/Shorts)", "16:9 Landscape (YouTube/TV)"],
        commercialUse: true,
      },
    ],
  },
  {
    creator: {
      name: "Alex Vance",
      username: "alexvance",
      email: "alex@vancestudios.ai",
      specialization: "Sci-Fi AI Filmmaker & Worldbuilder",
      bio: "Crafting atmospheric science-fiction epics, cinematic trailers, and architectural concept worlds with deep temporal coherence.",
      availability: "Available immediately",
      commercialUse: true,
      skills: [
        "Cinematic Worldbuilding",
        "Storyboarding & Animatics",
        "Prompt Engineering",
        "Voice Cloning & Audio Design",
        "Post-Processing & Upscaling",
      ],
      aiTools: ["Midjourney", "Runway", "ElevenLabs", "Topaz Video AI", "Premiere Pro"],
      aiModels: ["Runway Gen-3 Alpha", "OpenAI Sora", "Midjourney v6.1", "Claude 3.5 Sonnet"],
      contentTypes: [
        "Cinematic Trailers",
        "Brand Commercials",
        "Concept Art & Posters",
      ],
      formats: [
        "16:9 Landscape (YouTube/TV)",
        "21:9 Widescreen Cinema",
        "4K UHD",
      ],
      workflow:
        "World architecture prompt chaining in Claude, cinematic scene generation in Midjourney, shot synthesis in Runway Gen-3, ElevenLabs spatial sound design.",
      profilePhoto: "",
      socialLinks: {
        website: "https://vancestudios.ai",
        x: "https://x.com/alexvance_ai",
      },
      verified: true,
      verification: {
        tools: true,
        workflow: true,
        portfolio: true,
      },
      status: "Active",
      theme: "royal",
    },
    portfolio: [
      {
        id: "alex-p1",
        title: "Chronos Orbital Station",
        description: "Cinematic trailer sequence depicting orbital logistics and deep-space habitats in ultra-wide format.",
        mediaUrl: "/reels/reel-03.mp4",
        thumbnailUrl: "/reels/reel-03.jpg",
        contentType: "Cinematic Trailers",
        tools: ["Runway", "Midjourney"],
        models: ["Runway Gen-3 Alpha", "Midjourney v6.1"],
        skills: ["Cinematic Worldbuilding", "Camera Movement Control"],
        workflow: "Midjourney environments → Runway Gen-3 camera pan → Topaz 4K",
        formats: ["16:9 Landscape (YouTube/TV)", "4K UHD"],
        commercialUse: true,
      },
      {
        id: "alex-p2",
        title: "Cybernetic Genesis",
        description: "Hard-surface robotics and robotic biomechanics commercial showcase.",
        mediaUrl: "/reels/reel-04.mp4",
        thumbnailUrl: "/reels/reel-04.jpg",
        contentType: "Brand Commercials",
        tools: ["ComfyUI", "Topaz Video AI"],
        models: ["Flux.1 Dev", "SDXL / Stable Diffusion"],
        skills: ["Character Consistency", "Motion Tracking & VFX"],
        workflow: "Flux LoRA → ComfyUI AnimateDiff → Topaz Upscale",
        formats: ["16:9 Landscape (YouTube/TV)"],
        commercialUse: true,
      },
    ],
  },
  {
    creator: {
      name: "Elena Rostova",
      username: "elenarostova",
      email: "elena@atelier-ai.com",
      specialization: "Virtual Fashion & Luxury Visual Artist",
      bio: "High-end luxury aesthetic, digital textile simulation, and hyper-stylized editorial visuals for global fashion brands.",
      availability: "Open for select projects",
      commercialUse: true,
      skills: [
        "Style Transfer & LoRA Training",
        "Character Consistency",
        "Color Grading & Finishing",
        "Prompt Engineering",
      ],
      aiTools: ["Midjourney", "Magnific AI", "ComfyUI", "Photoshop AI"],
      aiModels: ["Flux.1 Dev", "Midjourney v6.1", "SDXL / Stable Diffusion"],
      contentTypes: [
        "Brand Commercials",
        "Concept Art & Posters",
        "Short-form Video (Reels/TikTok)",
      ],
      formats: [
        "9:16 Vertical (Reels/Shorts)",
        "4:5 Portrait",
        "1:1 Square (Instagram Post)",
      ],
      workflow:
        "Custom fashion LoRA models trained on luxury textiles, Midjourney v6.1 high-fashion generation, Magnific AI micro-texture upscaling.",
      profilePhoto: "",
      socialLinks: {
        website: "https://atelier-ai.com",
        instagram: "https://instagram.com/elena_atelier",
      },
      verified: true,
      verification: {
        tools: true,
        workflow: true,
        portfolio: true,
      },
      status: "Active",
      theme: "social",
    },
    portfolio: [
      {
        id: "elena-p1",
        title: "Metamorphosis Spring Lookbook",
        description: "Editorial video showcasing digital silk simulations and chromatic lighting for Milan Fashion Week digital drop.",
        mediaUrl: "/reels/reel-05.mp4",
        thumbnailUrl: "/reels/reel-05.jpg",
        contentType: "Short-form Video (Reels/TikTok)",
        tools: ["Midjourney", "Magnific AI"],
        models: ["Midjourney v6.1", "Flux.1 Dev"],
        skills: ["Style Transfer & LoRA Training", "Color Grading & Finishing"],
        workflow: "Custom silk LoRA → Magnific 8K upscale",
        formats: ["9:16 Vertical (Reels/Shorts)", "4:5 Portrait"],
        commercialUse: true,
      },
      {
        id: "elena-p2",
        title: "Obsidian Haute Couture",
        description: "Dark luxury campaign featuring bespoke jewelry and refractive glass lighting.",
        mediaUrl: "/reels/reel-06.mp4",
        thumbnailUrl: "/reels/reel-06.jpg",
        contentType: "Brand Commercials",
        tools: ["ComfyUI", "Photoshop AI"],
        models: ["Flux.1 Dev"],
        skills: ["Prompt Engineering", "Post-Processing & Upscaling"],
        workflow: "ComfyUI prompt sequencing → Photoshop AI retouching",
        formats: ["1:1 Square (Instagram Post)", "9:16 Vertical (Reels/Shorts)"],
        commercialUse: true,
      },
    ],
  },
  {
    creator: {
      name: "Kai Tanaka",
      username: "kaitanaka",
      email: "kai@neonmecha.jp",
      specialization: "Generative Anime & Motion Designer",
      bio: "Fusing classic Japanese animation cinematography with bleeding-edge AI diffusion and frame interpolation.",
      availability: "Available immediately",
      commercialUse: true,
      skills: [
        "Style Transfer & LoRA Training",
        "Character Consistency",
        "Camera Movement Control",
        "Storyboarding & Animatics",
      ],
      aiTools: ["ComfyUI", "Kling AI", "Midjourney", "After Effects"],
      aiModels: ["Kling 1.5", "SDXL / Stable Diffusion", "Flux.1 Dev"],
      contentTypes: [
        "Short-form Video (Reels/TikTok)",
        "Animated Shorts",
        "Music Videos",
      ],
      formats: [
        "9:16 Vertical (Reels/Shorts)",
        "16:9 Landscape (YouTube/TV)",
        "1080p Full HD",
      ],
      workflow:
        "Storyboarding in Procreate, ControlNet keyframing in ComfyUI, temporal motion interpolation in Kling 1.5, stylized cell grading in After Effects.",
      profilePhoto: "",
      socialLinks: {
        website: "https://neonmecha.jp",
        x: "https://x.com/kai_tanaka_ai",
      },
      verified: true,
      verification: {
        tools: true,
        workflow: true,
        portfolio: true,
      },
      status: "Active",
      theme: "neon",
    },
    portfolio: [
      {
        id: "kai-p1",
        title: "Cyber Mecha Chase Sequence",
        description: "Dynamic anime motorcycle pursuit in neo-Tokyo with rain reflections and speedlines.",
        mediaUrl: "/reels/reel-07.mp4",
        thumbnailUrl: "/reels/reel-07.jpg",
        contentType: "Animated Shorts",
        tools: ["Kling AI", "ComfyUI"],
        models: ["Kling 1.5", "SDXL / Stable Diffusion"],
        skills: ["Camera Movement Control", "Style Transfer & LoRA Training"],
        workflow: "ComfyUI AnimateDiff → Kling 1.5 upscale",
        formats: ["9:16 Vertical (Reels/Shorts)", "16:9 Landscape (YouTube/TV)"],
        commercialUse: true,
      },
    ],
  },
  {
    creator: {
      name: "Marcus Brody",
      username: "marcusbrody",
      email: "marcus@brodyvisuals.com",
      specialization: "3D Product VFX & Hyperreal CGI",
      bio: "Hardware, automotive, and consumer electronics product visualization with cinematic studio lighting and macro physics.",
      availability: "Part-time / Freelance",
      commercialUse: true,
      skills: [
        "Post-Processing & Upscaling",
        "Color Grading & Finishing",
        "Prompt Engineering",
        "Motion Tracking & VFX",
      ],
      aiTools: ["Topaz Video AI", "Midjourney", "Runway", "DaVinci Resolve"],
      aiModels: ["Runway Gen-3 Alpha", "Flux.1 Dev", "Midjourney v6.1"],
      contentTypes: [
        "Product Visualizations",
        "Brand Commercials",
        "Social Media Ads",
      ],
      formats: [
        "16:9 Landscape (YouTube/TV)",
        "1:1 Square (Instagram Post)",
        "4K UHD",
      ],
      workflow:
        "Photoreal studio lighting prompts in Flux.1, micro-movement camera rigs in Runway Gen-3, 60fps smoothing in Topaz Video AI.",
      profilePhoto: "",
      socialLinks: {
        website: "https://brodyvisuals.com",
      },
      verified: true,
      verification: {
        tools: true,
        workflow: false,
        portfolio: true,
      },
      status: "Active",
      theme: "flame",
    },
    portfolio: [
      {
        id: "marcus-p1",
        title: "Chronograph Precision Watch Spot",
        description: "Macro mechanical gear reveal with titanium brushed textures and sapphire crystal refractions.",
        mediaUrl: "/reels/reel-09.mp4",
        thumbnailUrl: "/reels/reel-09.jpg",
        contentType: "Product Visualizations",
        tools: ["Runway", "Topaz Video AI"],
        models: ["Runway Gen-3 Alpha", "Flux.1 Dev"],
        skills: ["Post-Processing & Upscaling", "Prompt Engineering"],
        workflow: "Flux prompt macro → Runway camera rotation → Topaz 4K 60fps",
        formats: ["16:9 Landscape (YouTube/TV)", "4K UHD"],
        commercialUse: true,
      },
    ],
  },
  {
    creator: {
      name: "Sophia Chen",
      username: "sophiachen",
      email: "sophia@viralaicreative.com",
      specialization: "Social-First AI Video Creator",
      bio: "Crafting viral high-retention short-form video hooks for consumer brands, DTC startups, and TikTok marketing campaigns.",
      availability: "Available immediately",
      commercialUse: true,
      skills: [
        "Prompt Engineering",
        "Camera Movement Control",
        "Storyboarding & Animatics",
      ],
      aiTools: ["Pika", "Hailuo / Minimax", "ElevenLabs", "Photoshop AI"],
      aiModels: ["MiniMax Video-01", "Midjourney v6.1", "Runway Gen-3 Alpha"],
      contentTypes: [
        "Short-form Video (Reels/TikTok)",
        "Social Media Ads",
      ],
      formats: [
        "9:16 Vertical (Reels/Shorts)",
        "1080p Full HD",
      ],
      workflow:
        "Fast-turnaround iterative prompts in Hailuo / Minimax, ElevenLabs dynamic voiceover, CapCut social overlays.",
      profilePhoto: "",
      socialLinks: {
        x: "https://x.com/sophiachen_ai",
      },
      verified: true,
      verification: {
        tools: true,
        workflow: true,
        portfolio: true,
      },
      status: "Active",
      theme: "social",
    },
    portfolio: [
      {
        id: "sophia-p1",
        title: "Glow Serum Viral Reel",
        description: "High-retention 15-second TikTok ad hook showcasing transformation effect.",
        mediaUrl: "/reels/reel-11.mp4",
        thumbnailUrl: "/reels/reel-11.jpg",
        contentType: "Short-form Video (Reels/TikTok)",
        tools: ["Hailuo / Minimax", "ElevenLabs"],
        models: ["MiniMax Video-01"],
        skills: ["Prompt Engineering"],
        workflow: "Minimax text-to-video → ElevenLabs VO",
        formats: ["9:16 Vertical (Reels/Shorts)"],
        commercialUse: true,
      },
    ],
  },
];

export const DEMO_BRAND: BrandProfile = {
  id: "apex-athletics",
  ownerUid: "demo-brand-owner",
  name: "Apex Athletics",
  industry: "Sportswear & Athletic Innovation",
  description: "Next-generation running and lifestyle brand pushing physical and digital boundaries with biometric apparel and shoes.",
  contactEmail: "campaigns@apexathletics.com",
};

export const DEMO_BRIEFS: CreativeBrief[] = [
  {
    id: "brief-sneaker-01",
    brandId: "apex-athletics",
    brandName: "Apex Athletics",
    campaignName: "Futuristic Gen-Z Running Shoe Launch",
    requirements:
      "I need a futuristic 30-second Instagram reel for our new running shoe targeting Gen Z. It should feel energetic and cinematic and we need commercial rights. Consistent runner character in neon cyberpunk cityscape.",
    contentType: "Short-form Video (Reels/TikTok)",
    style: ["Futuristic", "Cinematic", "High-Energy", "Cyberpunk / Neon"],
    platform: "Instagram Reels & TikTok",
    aspectRatio: "9:16 Vertical (Reels/Shorts)",
    targetAudience: "Gen Z Trendsetters & Digital Natives (16-24)",
    deliverables: [
      "1x 30-Second Hero Video Deliverable (9:16)",
      "3x High-Res Still Keyframes",
      "1x Clean Cut for Social Ads",
    ],
    commercialUse: true,
    notes: "Audio sound design must sync with kinetic shoe impacts.",
    status: "Published",
  },
  {
    id: "brief-apparel-02",
    brandId: "apex-athletics",
    brandName: "Apex Athletics",
    campaignName: "Cyberpunk Techwear Apparel Showcase",
    requirements:
      "A cinematic 45-second 16:9 brand film highlighting water-repellent techwear fabric in rainy dystopian urban aesthetic.",
    contentType: "Brand Commercials",
    style: ["Cinematic", "Luxury Aesthetic", "Moody & Atmospheric"],
    platform: "YouTube & Web Video",
    aspectRatio: "16:9 Landscape (YouTube/TV)",
    targetAudience: "Urban Professionals & Tech Enthusiasts (25-40)",
    deliverables: [
      "1x 45-Second 4K Master Video",
      "Cutdowns for YouTube Pre-roll (15s)",
    ],
    commercialUse: true,
    notes: "Requires photorealistic rain particles and dark metallic reflections.",
    status: "Published",
  },
];
