import { CreatorProfile, PortfolioItem, BrandProfile, CreativeBrief } from "./types";

export type DemoCreatorWithPortfolio = {
  creator: CreatorProfile;
  portfolio: PortfolioItem[];
};

export const DEMO_CREATORS: DemoCreatorWithPortfolio[] = [
  // 1. Paul Trillo
  {
    creator: {
      name: "Paul Trillo",
      username: "paultrillo",
      email: "paul@paultrillo.com",
      specialization: "AI Film Director & Experimental VFX Pioneer",
      bio: "World-renowned writer and director pioneering generative AI filmmaking. Known for groundbreaking music videos, commercial direction for top global brands, and pushing the frontiers of OpenAI Sora, Runway, and Kling video synthesis.",
      availability: "Available for Select Commissions",
      commercialUse: true,
      skills: [
        "Cinematic Directing",
        "Dynamic Camera Trajectories",
        "Generative VFX & Compositing",
        "Optical Flow Dynamics",
        "Character Continuity",
        "Motion Vectoring",
        "Color Grading & Finishing",
      ],
      aiTools: [
        "Runway",
        "OpenAI Sora",
        "Kling AI",
        "Midjourney",
        "ComfyUI",
        "DaVinci Resolve",
        "After Effects",
      ],
      aiModels: [
        "Runway Gen-3 Alpha",
        "OpenAI Sora",
        "Kling 1.5",
        "Midjourney v6.1",
        "Flux.1 Dev",
      ],
      contentTypes: [
        "Cinematic Trailers",
        "Brand Commercials",
        "Music Videos",
        "Experimental Short Films",
      ],
      formats: [
        "16:9 Cinema",
        "9:16 Vertical (Reels/Shorts)",
        "4K UHD",
        "21:9 Widescreen Cinema",
      ],
      workflow:
        "Custom multi-engine directorial pipeline: ideation and keyframing via Midjourney & Flux, temporal video generation through Runway Gen-3 & Kling with advanced camera tracking, post-compositing in After Effects, and 4K mastering in DaVinci Resolve.",
      profilePhoto: "/creators/paultrillo/pfp.jpg",
      socialLinks: {
        website: "https://paultrillo.com",
        x: "https://x.com/paultrillo",
        instagram: "https://instagram.com/paultrillo",
      },
      verified: true,
      verification: {
        tools: true,
        workflow: true,
        portfolio: true,
      },
      status: "Active",
      theme: "flame",
    },
    portfolio: [
      {
        id: "trillo-r1",
        title: "Infinite Perspective Warp",
        description: "Kinetic camera acceleration pushing through dimensional architectural frames using Sora and Gen-3.",
        mediaUrl: "/creators/paultrillo/reels/reel-1.mp4",
        thumbnailUrl: "/creators/paultrillo/reels/reel-1.jpg",
        contentType: "Experimental Short Films",
        tools: ["Runway", "OpenAI Sora", "DaVinci Resolve"],
        models: ["Runway Gen-3 Alpha", "OpenAI Sora"],
        skills: ["Dynamic Camera Trajectories", "Optical Flow Dynamics"],
        workflow: "Direct prompt trajectory → Runway camera vectoring → DaVinci color grading",
        formats: ["9:16 Vertical (Reels/Shorts)", "4K UHD"],
        commercialUse: true,
      },
      {
        id: "trillo-r2",
        title: "Choreographed Chromatic Fluidity",
        description: "Surreal physical simulation of garments and kinetic dance motion synthesizing digital physics.",
        mediaUrl: "/creators/paultrillo/reels/reel-2.mp4",
        thumbnailUrl: "/creators/paultrillo/reels/reel-2.jpg",
        contentType: "Music Videos",
        tools: ["Kling AI", "After Effects"],
        models: ["Kling 1.5", "Flux.1 Dev"],
        skills: ["Motion Vectoring", "Generative VFX & Compositing"],
        workflow: "Flux character anchors → Kling temporal interpolation → After Effects composite",
        formats: ["9:16 Vertical (Reels/Shorts)"],
        commercialUse: true,
      },
      {
        id: "trillo-r3",
        title: "Metamorphic Urban Shift",
        description: "Continuous tracking shot shifting architectural eras from brutalism to futuristic organic structures.",
        mediaUrl: "/creators/paultrillo/reels/reel-3.mp4",
        thumbnailUrl: "/creators/paultrillo/reels/reel-3.jpg",
        contentType: "Cinematic Trailers",
        tools: ["Runway", "Midjourney"],
        models: ["Runway Gen-3 Alpha", "Midjourney v6.1"],
        skills: ["Cinematic Directing", "Character Continuity"],
        workflow: "Midjourney keyframe anchors → Runway temporal transition → 4K master",
        formats: ["9:16 Vertical (Reels/Shorts)", "4K UHD"],
        commercialUse: true,
      },
      {
        id: "trillo-r4",
        title: "Kinetic Velocity Experiment",
        description: "High-speed camera motion exploring optical shutter drag and photorealistic lens aberrations.",
        mediaUrl: "/creators/paultrillo/reels/reel-4.mp4",
        thumbnailUrl: "/creators/paultrillo/reels/reel-4.jpg",
        contentType: "Brand Commercials",
        tools: ["Runway", "Topaz Video AI"],
        models: ["Runway Gen-3 Alpha"],
        skills: ["Dynamic Camera Trajectories", "Color Grading & Finishing"],
        workflow: "Runway prompt engineering → Topaz temporal stabilization",
        formats: ["9:16 Vertical (Reels/Shorts)"],
        commercialUse: true,
      },
      {
        id: "trillo-r5",
        title: "Atmospheric Dreamscape Portal",
        description: "Multilayered generative composition exploring optical illusion and spatial distortion.",
        mediaUrl: "/creators/paultrillo/reels/reel-5.mp4",
        thumbnailUrl: "/creators/paultrillo/reels/reel-5.jpg",
        contentType: "Experimental Short Films",
        tools: ["OpenAI Sora", "After Effects"],
        models: ["OpenAI Sora", "Midjourney v6.1"],
        skills: ["Generative VFX & Compositing", "Cinematic Directing"],
        workflow: "Sora direct simulation → After Effects multi-pass compositing",
        formats: ["9:16 Vertical (Reels/Shorts)", "4K UHD"],
        commercialUse: true,
      },
    ],
  },

  // 2. Nicolas Neubert
  {
    creator: {
      name: "Nicolas Neubert",
      username: "nicolasneubert",
      email: "nicolas@neubert.studio",
      specialization: "Sci-Fi AI Worldbuilder & Cinematic Director",
      bio: "Senior AI Creative Director and creator of the viral sci-fi project 'Genesis'. World authority on complex architectural worldbuilding, dystopian aesthetics, and multi-shot narrative consistency using Midjourney and Runway.",
      availability: "Available immediately",
      commercialUse: true,
      skills: [
        "Cinematic Worldbuilding",
        "Spatial Architecture",
        "Prompt Chaining & Anchor Keyframing",
        "Temporal Narrative Coherence",
        "Sound Design & Spatial Audio",
        "Color Science & Atmosphere",
      ],
      aiTools: [
        "Midjourney",
        "Runway",
        "ElevenLabs",
        "Topaz Video AI",
        "Premiere Pro",
      ],
      aiModels: [
        "Runway Gen-3 Alpha",
        "Midjourney v6.1",
        "Flux.1 Schnell",
        "ElevenLabs Voice",
      ],
      contentTypes: [
        "Cinematic Trailers",
        "Sci-Fi Worldbuilding",
        "Brand Commercials",
        "Concept Art & Posters",
      ],
      formats: [
        "21:9 Widescreen Cinema",
        "16:9 Landscape (YouTube/TV)",
        "9:16 Vertical (Reels/Shorts)",
        "4K UHD",
      ],
      workflow:
        "Iterative style-anchored keyframing in Midjourney v6.1, cinematic camera pans & atmospheric volumetric lighting synthesis in Runway Gen-3, 4K temporal upscaling in Topaz Video AI, integrated with custom ElevenLabs audio soundscapes.",
      profilePhoto: "/creators/nicolasneubert/pfp.jpg",
      socialLinks: {
        website: "https://neubert.studio",
        x: "https://x.com/iamneubert",
        instagram: "https://instagram.com/iamneubert",
      },
      verified: true,
      verification: {
        tools: true,
        workflow: true,
        portfolio: true,
      },
      status: "Active",
      theme: "royal",
    },
    portfolio: [
      {
        id: "neubert-r1",
        title: "Genesis — The Dystopian Horizon",
        description: "Official trailer sequence showcasing monolithic mega-structures, zero-gravity logistics, and cinematic atmosphere.",
        mediaUrl: "/creators/nicolasneubert/reels/reel-1.mp4",
        thumbnailUrl: "/creators/nicolasneubert/reels/reel-1.jpg",
        contentType: "Cinematic Trailers",
        tools: ["Midjourney", "Runway", "Topaz Video AI"],
        models: ["Midjourney v6.1", "Runway Gen-3 Alpha"],
        skills: ["Cinematic Worldbuilding", "Color Science & Atmosphere"],
        workflow: "Midjourney style anchors → Runway Gen-3 camera sweep → Topaz 4K upscale",
        formats: ["9:16 Vertical (Reels/Shorts)", "4K UHD"],
        commercialUse: true,
      },
      {
        id: "neubert-r2",
        title: "Orbital Relay Command",
        description: "Deep-space transmission station sequence featuring realistic telemetry lighting and mechanical textures.",
        mediaUrl: "/creators/nicolasneubert/reels/reel-2.mp4",
        thumbnailUrl: "/creators/nicolasneubert/reels/reel-2.jpg",
        contentType: "Sci-Fi Worldbuilding",
        tools: ["Runway", "Midjourney"],
        models: ["Runway Gen-3 Alpha", "Midjourney v6.1"],
        skills: ["Spatial Architecture", "Temporal Narrative Coherence"],
        workflow: "Midjourney concept pass → Runway shot extension → 4K finish",
        formats: ["9:16 Vertical (Reels/Shorts)"],
        commercialUse: true,
      },
      {
        id: "neubert-r3",
        title: "Subterranean Cybernetics Lab",
        description: "Underground biomechanics prototyping facility with moody teal-orange cinematic grade.",
        mediaUrl: "/creators/nicolasneubert/reels/reel-3.mp4",
        thumbnailUrl: "/creators/nicolasneubert/reels/reel-3.jpg",
        contentType: "Brand Commercials",
        tools: ["Runway", "ElevenLabs"],
        models: ["Runway Gen-3 Alpha", "ElevenLabs Voice"],
        skills: ["Sound Design & Spatial Audio", "Color Science & Atmosphere"],
        workflow: "Runway prompt choreography → Spatial SFX master",
        formats: ["9:16 Vertical (Reels/Shorts)", "4K UHD"],
        commercialUse: true,
      },
      {
        id: "neubert-r4",
        title: "Titan Colony Atmos Flight",
        description: "Low-altitude cruiser flight over cryogenic methane oceans with hyper-detailed cloud physics.",
        mediaUrl: "/creators/nicolasneubert/reels/reel-4.mp4",
        thumbnailUrl: "/creators/nicolasneubert/reels/reel-4.jpg",
        contentType: "Cinematic Trailers",
        tools: ["Midjourney", "Runway"],
        models: ["Midjourney v6.1", "Runway Gen-3 Alpha"],
        skills: ["Cinematic Worldbuilding", "Prompt Chaining & Anchor Keyframing"],
        workflow: "Style anchor prompt chain → Runway horizontal dolly zoom",
        formats: ["9:16 Vertical (Reels/Shorts)"],
        commercialUse: true,
      },
      {
        id: "neubert-r5",
        title: "Sentient Core Awakening",
        description: "Quantum supercomputer cluster ignition with glowing crystalline optical filaments.",
        mediaUrl: "/creators/nicolasneubert/reels/reel-5.mp4",
        thumbnailUrl: "/creators/nicolasneubert/reels/reel-5.jpg",
        contentType: "Sci-Fi Worldbuilding",
        tools: ["Runway", "Premiere Pro"],
        models: ["Runway Gen-3 Alpha"],
        skills: ["Spatial Architecture", "Cinematic Worldbuilding"],
        workflow: "Runway generative video → Premiere editorial cut",
        formats: ["9:16 Vertical (Reels/Shorts)", "4K UHD"],
        commercialUse: true,
      },
    ],
  },

  // 3. Julie Wieland
  {
    creator: {
      name: "Julie Wieland",
      username: "juliewieland",
      email: "julie@juliewieland.com",
      specialization: "AI Cinematographer & Editorial Fashion Visualizer",
      bio: "Celebrated AI filmmaker and visual artist specializing in analog film textures, evocative character portraits, high-fashion editorial aesthetics, and intimate cinematic lighting.",
      availability: "Available for Select Campaigns",
      commercialUse: true,
      skills: [
        "Analog Film Emulation",
        "Editorial Lighting & Shading",
        "Character Consistency",
        "Fashion & Luxury Styling",
        "Lens Dispersion & Depth of Field",
        "Editorial Storyboarding",
      ],
      aiTools: [
        "Midjourney",
        "Magnific AI",
        "Runway",
        "Luma Dream Machine",
        "Photoshop",
        "DaVinci Resolve",
      ],
      aiModels: [
        "Midjourney v6.1",
        "Flux.1 Dev",
        "Runway Gen-3 Alpha",
        "Luma Ray 2",
      ],
      contentTypes: [
        "Fashion Films",
        "Brand Commercials",
        "Editorial Video",
        "Short-form Video (Reels/TikTok)",
      ],
      formats: [
        "16:9 Landscape (YouTube/TV)",
        "9:16 Vertical (Reels/Shorts)",
        "4:5 Portrait",
        "4K UHD",
      ],
      workflow:
        "Fine-tuned aesthetic prompting in Midjourney & Flux.1 Dev, dynamic micro-texture upscaling with Magnific AI, cinematic camera drift synthesis in Runway Gen-3 & Luma, and 35mm Kodak film grain emulation in DaVinci Resolve.",
      profilePhoto: "/creators/juliewieland/pfp.jpg",
      socialLinks: {
        website: "https://juliewieland.com",
        x: "https://x.com/juliewieland",
        instagram: "https://instagram.com/juliewieland",
      },
      verified: true,
      verification: {
        tools: true,
        workflow: true,
        portfolio: true,
      },
      status: "Active",
      theme: "neon",
    },
    portfolio: [
      {
        id: "wieland-r1",
        title: "Velvet Eclipse — Haute Horlogerie",
        description: "Editorial luxury timepiece commercial with fluid shadows, refractive glass prisms, and 35mm grain.",
        mediaUrl: "/creators/juliewieland/reels/reel-1.mp4",
        thumbnailUrl: "/creators/juliewieland/reels/reel-1.jpg",
        contentType: "Fashion Films",
        tools: ["Midjourney", "Runway", "DaVinci Resolve"],
        models: ["Midjourney v6.1", "Runway Gen-3 Alpha"],
        skills: ["Editorial Lighting & Shading", "Analog Film Emulation"],
        workflow: "Midjourney character keyframes → Runway slow drift → Kodak 35mm LUT",
        formats: ["16:9 Landscape (YouTube/TV)", "4K UHD"],
        commercialUse: true,
      },
      {
        id: "wieland-r2",
        title: "Silk Metamorphosis",
        description: "Digital haute couture showcase featuring fluid textile physics and soft golden hour illumination.",
        mediaUrl: "/creators/juliewieland/reels/reel-2.mp4",
        thumbnailUrl: "/creators/juliewieland/reels/reel-2.jpg",
        contentType: "Brand Commercials",
        tools: ["Flux.1 Dev", "Luma Dream Machine"],
        models: ["Flux.1 Dev", "Luma Ray 2"],
        skills: ["Fashion & Luxury Styling", "Lens Dispersion & Depth of Field"],
        workflow: "Flux prompt tuning → Luma temporal camera interpolation",
        formats: ["16:9 Landscape (YouTube/TV)"],
        commercialUse: true,
      },
      {
        id: "wieland-r3",
        title: "Chromance — Intimate Portraiture",
        description: "Close-up emotive character study exploring subsurface skin scattering and micro-expressions.",
        mediaUrl: "/creators/juliewieland/reels/reel-3.mp4",
        thumbnailUrl: "/creators/juliewieland/reels/reel-3.jpg",
        contentType: "Editorial Video",
        tools: ["Midjourney", "Magnific AI"],
        models: ["Midjourney v6.1", "Flux.1 Dev"],
        skills: ["Character Consistency", "Editorial Lighting & Shading"],
        workflow: "Midjourney facial anchor → Magnific 8K skin upscaler",
        formats: ["16:9 Landscape (YouTube/TV)", "4K UHD"],
        commercialUse: true,
      },
      {
        id: "wieland-r4",
        title: "Noir Botanica",
        description: "Moody floral composition blending dark botanical motifs with high-fashion jewelry.",
        mediaUrl: "/creators/juliewieland/reels/reel-4.mp4",
        thumbnailUrl: "/creators/juliewieland/reels/reel-4.jpg",
        contentType: "Fashion Films",
        tools: ["Runway", "Photoshop"],
        models: ["Runway Gen-3 Alpha"],
        skills: ["Editorial Storyboarding", "Analog Film Emulation"],
        workflow: "Runway macro camera rotation → Photoshop color matching",
        formats: ["16:9 Landscape (YouTube/TV)"],
        commercialUse: true,
      },
      {
        id: "wieland-r5",
        title: "Elysian Solitude",
        description: "Minimalist architectural fashion film featuring clean limestone geometries and sculptural drapery.",
        mediaUrl: "/creators/juliewieland/reels/reel-5.mp4",
        thumbnailUrl: "/creators/juliewieland/reels/reel-5.jpg",
        contentType: "Brand Commercials",
        tools: ["Midjourney", "Runway"],
        models: ["Midjourney v6.1", "Runway Gen-3 Alpha"],
        skills: ["Fashion & Luxury Styling", "Character Consistency"],
        workflow: "Architectural prompt styling → Runway lateral pan",
        formats: ["16:9 Landscape (YouTube/TV)", "4K UHD"],
        commercialUse: true,
      },
    ],
  },

  // 4. Kavan Cardoza
  {
    creator: {
      name: "Kavan Cardoza",
      username: "kavancardoza",
      email: "kavan@thekid.studio",
      specialization: "AI Surrealist & High-Concept VFX Director",
      bio: "Visionary visual artist and director known as Kavan The Kid. Blends surreal dark fantasy, practical VFX sensibilities, and cutting-edge generative AI to craft hauntingly poetic, high-impact visual stories.",
      availability: "Available immediately",
      commercialUse: true,
      skills: [
        "Surreal World Design",
        "Complex Particle FX",
        "Physical Motion Tracking",
        "Lighting Dynamics & Shadows",
        "Practical & AI Hybrid VFX",
        "Creative Concept Pitching",
      ],
      aiTools: [
        "Runway",
        "ComfyUI",
        "Midjourney",
        "Blender",
        "After Effects",
        "EbSynth",
      ],
      aiModels: [
        "Runway Gen-3 Alpha",
        "Flux.1 Dev",
        "Stable Diffusion XL",
        "Kling 1.5",
      ],
      contentTypes: [
        "Music Videos",
        "Surreal Brand Spots",
        "Cinematic Trailers",
        "Visual Effects",
      ],
      formats: [
        "16:9 Landscape (YouTube/TV)",
        "9:16 Vertical (Reels/Shorts)",
        "4K UHD",
      ],
      workflow:
        "Hybrid 3D block-in with Blender, diffusion texture generation via ComfyUI ControlNet, camera kinetics in Runway Gen-3 & Kling 1.5, and seamless multi-layer compositing in After Effects.",
      profilePhoto: "/creators/kavancardoza/pfp.jpg",
      socialLinks: {
        website: "https://kavanthekid.com",
        instagram: "https://instagram.com/kavanthekid",
        x: "https://x.com/kavanthekid",
      },
      verified: true,
      verification: {
        tools: true,
        workflow: true,
        portfolio: true,
      },
      status: "Active",
      theme: "social",
    },
    portfolio: [
      {
        id: "cardoza-r1",
        title: "Gravity's Memory",
        description: "Poetic visual sequence featuring levitating antique furniture and kinetic rain particles.",
        mediaUrl: "/creators/kavancardoza/reels/reel-1.mp4",
        thumbnailUrl: "/creators/kavancardoza/reels/reel-1.jpg",
        contentType: "Music Videos",
        tools: ["Runway", "Blender", "After Effects"],
        models: ["Runway Gen-3 Alpha", "Flux.1 Dev"],
        skills: ["Surreal World Design", "Complex Particle FX"],
        workflow: "Blender 3D camera tracker → Runway generative overlay → After Effects comp",
        formats: ["16:9 Landscape (YouTube/TV)", "4K UHD"],
        commercialUse: true,
      },
      {
        id: "cardoza-r2",
        title: "The Rust Cathedral",
        description: "Monumental crumbling industrial church with bioluminescent botanical overgrowth.",
        mediaUrl: "/creators/kavancardoza/reels/reel-2.mp4",
        thumbnailUrl: "/creators/kavancardoza/reels/reel-2.jpg",
        contentType: "Cinematic Trailers",
        tools: ["ComfyUI", "Runway"],
        models: ["Flux.1 Dev", "Runway Gen-3 Alpha"],
        skills: ["Lighting Dynamics & Shadows", "Practical & AI Hybrid VFX"],
        workflow: "ComfyUI depth control → Runway camera push-in",
        formats: ["16:9 Landscape (YouTube/TV)"],
        commercialUse: true,
      },
      {
        id: "cardoza-r3",
        title: "Phantasmagoria Smoke Mirage",
        description: "High-speed fluid smoke simulation transforming into fleeting human silhouettes.",
        mediaUrl: "/creators/kavancardoza/reels/reel-3.mp4",
        thumbnailUrl: "/creators/kavancardoza/reels/reel-3.jpg",
        contentType: "Surreal Brand Spots",
        tools: ["Kling AI", "After Effects"],
        models: ["Kling 1.5"],
        skills: ["Physical Motion Tracking", "Surreal World Design"],
        workflow: "Kling video interpolation → After Effects particle glow",
        formats: ["16:9 Landscape (YouTube/TV)", "4K UHD"],
        commercialUse: true,
      },
      {
        id: "cardoza-r4",
        title: "Clockwork Heartbeat",
        description: "Macro mechanical gears merging organically with cardiovascular anatomical art.",
        mediaUrl: "/creators/kavancardoza/reels/reel-4.mp4",
        thumbnailUrl: "/creators/kavancardoza/reels/reel-4.jpg",
        contentType: "Visual Effects",
        tools: ["Runway", "Midjourney"],
        models: ["Runway Gen-3 Alpha", "Midjourney v6.1"],
        skills: ["Practical & AI Hybrid VFX", "Complex Particle FX"],
        workflow: "Midjourney concept anchors → Runway camera orbital move",
        formats: ["16:9 Landscape (YouTube/TV)"],
        commercialUse: true,
      },
      {
        id: "cardoza-r5",
        title: "The Obsidian Mirror",
        description: "Dark reflective surface portal reflecting alternate surreal dimensions under twilight sky.",
        mediaUrl: "/creators/kavancardoza/reels/reel-5.mp4",
        thumbnailUrl: "/creators/kavancardoza/reels/reel-5.jpg",
        contentType: "Surreal Brand Spots",
        tools: ["Runway", "ComfyUI"],
        models: ["Runway Gen-3 Alpha", "Flux.1 Dev"],
        skills: ["Surreal World Design", "Lighting Dynamics & Shadows"],
        workflow: "ComfyUI ControlNet → Runway video pass",
        formats: ["16:9 Landscape (YouTube/TV)", "4K UHD"],
        commercialUse: true,
      },
    ],
  },

  // 5. Kyle Kesterson
  {
    creator: {
      name: "Kyle Kesterson",
      username: "kylekesterson",
      email: "kyle@kesterson.ai",
      specialization: "AI Storyteller & Spatial Narrative Director",
      bio: "Narrative designer, serial entrepreneur, and AI visual storyteller. Explores the frontiers of human-AI co-creation, emotional worldbuilding, and interactive mythology across spatial mediums.",
      availability: "Available for Consultations & Production",
      commercialUse: true,
      skills: [
        "Narrative Design & Lore",
        "Character Voice & Persona",
        "Spatial Storytelling",
        "Prompt Architecture",
        "Rapid Ideation & Prototyping",
        "Transmedia Brand Universes",
      ],
      aiTools: [
        "Midjourney",
        "Runway",
        "Claude 3.5 Sonnet",
        "ElevenLabs",
        "Premiere Pro",
      ],
      aiModels: [
        "Runway Gen-3 Alpha",
        "Midjourney v6.1",
        "Claude 3.5 Sonnet",
        "Flux.1 Dev",
      ],
      contentTypes: [
        "Narrative Shorts",
        "Brand Mythology",
        "Concept Trailers",
        "Experiential Media",
      ],
      formats: [
        "4:3 Narrative",
        "16:9 Landscape (YouTube/TV)",
        "9:16 Vertical (Reels/Shorts)",
        "1080p Full HD",
      ],
      workflow:
        "Iterative narrative drafting in Claude 3.5, stylized world creation in Midjourney & Flux, motion animation in Runway Gen-3, and voice synthesis in ElevenLabs.",
      profilePhoto: "/creators/kylekesterson/pfp.jpg",
      socialLinks: {
        website: "https://kylekesterson.com",
        x: "https://x.com/kylekesterson",
        instagram: "https://instagram.com/kylekesterson",
      },
      verified: true,
      verification: {
        tools: true,
        workflow: true,
        portfolio: true,
      },
      status: "Active",
      theme: "flame",
    },
    portfolio: [
      {
        id: "kesterson-r1",
        title: "The Wanderer's Compass",
        description: "Emotional animated journey of an explorer discovering hidden biomes across uncharted islands.",
        mediaUrl: "/creators/kylekesterson/reels/reel-1.mp4",
        thumbnailUrl: "/creators/kylekesterson/reels/reel-1.jpg",
        contentType: "Narrative Shorts",
        tools: ["Midjourney", "Runway", "ElevenLabs"],
        models: ["Midjourney v6.1", "Runway Gen-3 Alpha"],
        skills: ["Narrative Design & Lore", "Spatial Storytelling"],
        workflow: "Story drafting in Claude → Midjourney character anchoring → Runway animation",
        formats: ["4:3 Narrative", "1080p Full HD"],
        commercialUse: true,
      },
      {
        id: "kesterson-r2",
        title: "Myth of the Firekeeper",
        description: "Folklore animation exploring indigenous storytelling themes and tactile woodcut textures.",
        mediaUrl: "/creators/kylekesterson/reels/reel-2.mp4",
        thumbnailUrl: "/creators/kylekesterson/reels/reel-2.jpg",
        contentType: "Brand Mythology",
        tools: ["Runway", "Claude 3.5 Sonnet"],
        models: ["Runway Gen-3 Alpha", "Claude 3.5 Sonnet"],
        skills: ["Character Voice & Persona", "Prompt Architecture"],
        workflow: "Claude lore generation → Runway texture synthesis",
        formats: ["4:3 Narrative"],
        commercialUse: true,
      },
      {
        id: "kesterson-r3",
        title: "Echoes of the Canopy",
        description: "Atmospheric exploration of ancient primeval redwoods inhabited by spiritual entities.",
        mediaUrl: "/creators/kylekesterson/reels/reel-3.mp4",
        thumbnailUrl: "/creators/kylekesterson/reels/reel-3.jpg",
        contentType: "Experiential Media",
        tools: ["Midjourney", "Runway"],
        models: ["Midjourney v6.1", "Flux.1 Dev"],
        skills: ["Spatial Storytelling", "Rapid Ideation & Prototyping"],
        workflow: "Midjourney concept sketches → Runway camera tracking",
        formats: ["4:3 Narrative", "1080p Full HD"],
        commercialUse: true,
      },
      {
        id: "kesterson-r4",
        title: "The Solitary Astronomer",
        description: "Silent animated short following an astronomer chronicling comets from a cliffside dome.",
        mediaUrl: "/creators/kylekesterson/reels/reel-4.mp4",
        thumbnailUrl: "/creators/kylekesterson/reels/reel-4.jpg",
        contentType: "Narrative Shorts",
        tools: ["Runway", "Premiere Pro"],
        models: ["Runway Gen-3 Alpha"],
        skills: ["Narrative Design & Lore", "Character Voice & Persona"],
        workflow: "Runway video rendering → Premiere editorial cut",
        formats: ["4:3 Narrative"],
        commercialUse: true,
      },
      {
        id: "kesterson-r5",
        title: "Origins of the Celestial Map",
        description: "Cartographic fantasy short showing parchment maps animating into living three-dimensional worlds.",
        mediaUrl: "/creators/kylekesterson/reels/reel-5.mp4",
        thumbnailUrl: "/creators/kylekesterson/reels/reel-5.jpg",
        contentType: "Concept Trailers",
        tools: ["Midjourney", "Runway"],
        models: ["Midjourney v6.1", "Runway Gen-3 Alpha"],
        skills: ["Transmedia Brand Universes", "Prompt Architecture"],
        workflow: "Map illustration concept → Runway multi-scale zoom",
        formats: ["4:3 Narrative", "1080p Full HD"],
        commercialUse: true,
      },
    ],
  },

  // 6. Digital da Vincis
  {
    creator: {
      name: "Digital da Vincis",
      username: "digitaldavincis",
      email: "hello@digitaldavincis.com",
      specialization: "AI Creative Studio & Commercial Innovation Lab",
      bio: "Elite creative AI studio producing future-facing commercial campaigns, luxury product visualizers, and kinetic brand identities for global Fortune 500 agencies.",
      availability: "Available for Agency Bookings",
      commercialUse: true,
      skills: [
        "Brand Commercial Direction",
        "Fluid Simulation & Liquid Dynamics",
        "Product Hero Animations",
        "Multi-Format Campaign Delivery",
        "Agency Pitch Decks & Proofs",
        "Commercial IP Clearance",
      ],
      aiTools: [
        "Runway",
        "Kling AI",
        "Midjourney",
        "ComfyUI",
        "Topaz Video AI",
        "Cinema 4D",
      ],
      aiModels: [
        "Runway Gen-3 Alpha",
        "Kling 1.5",
        "Flux.1 Dev",
        "Midjourney v6.1",
      ],
      contentTypes: [
        "Brand Commercials",
        "Product Visualizers",
        "Social Media Ads",
        "Short-form Video (Reels/TikTok)",
      ],
      formats: [
        "9:16 Vertical (Reels/Shorts)",
        "16:9 Landscape (YouTube/TV)",
        "1:1 Square (Instagram Post)",
        "4K UHD",
      ],
      workflow:
        "Full agency pipeline: concept boards in Midjourney, 3D asset tracking with Cinema 4D, high-velocity video generation with Kling & Runway, 4K multi-format delivery.",
      profilePhoto: "/creators/digitaldavincis/pfp.jpg",
      socialLinks: {
        website: "https://digitaldavincis.com",
        instagram: "https://instagram.com/digitaldavincis",
        x: "https://x.com/digitaldavincis",
      },
      verified: true,
      verification: {
        tools: true,
        workflow: true,
        portfolio: true,
      },
      status: "Active",
      theme: "royal",
    },
    portfolio: [
      {
        id: "davincis-r1",
        title: "Aura Hyper-Sneaker Teaser",
        description: "Kinetic commercial teaser for high-performance athletic footwear with floating particle fields.",
        mediaUrl: "/creators/digitaldavincis/reels/reel-1.mp4",
        thumbnailUrl: "/creators/digitaldavincis/reels/reel-1.jpg",
        contentType: "Brand Commercials",
        tools: ["Runway", "Midjourney", "Cinema 4D"],
        models: ["Runway Gen-3 Alpha", "Midjourney v6.1"],
        skills: ["Product Hero Animations", "Brand Commercial Direction"],
        workflow: "3D camera pass in Cinema 4D → Runway generative skinning → Topaz 4K",
        formats: ["16:9 Landscape (YouTube/TV)", "4K UHD"],
        commercialUse: true,
      },
      {
        id: "davincis-r2",
        title: "Luminescence Fluid Drink",
        description: "High-energy beverage commercial featuring zero-gravity liquid splashes and carbonation physics.",
        mediaUrl: "/creators/digitaldavincis/reels/reel-2.mp4",
        thumbnailUrl: "/creators/digitaldavincis/reels/reel-2.jpg",
        contentType: "Product Visualizers",
        tools: ["Kling AI", "ComfyUI"],
        models: ["Kling 1.5", "Flux.1 Dev"],
        skills: ["Fluid Simulation & Liquid Dynamics", "Product Hero Animations"],
        workflow: "ComfyUI liquid simulation prompts → Kling temporal interpolation",
        formats: ["16:9 Landscape (YouTube/TV)"],
        commercialUse: true,
      },
      {
        id: "davincis-r3",
        title: "Cyberpunk Kinetic Reveal",
        description: "Dynamic automotive reveal under rainy neon city streetlights with optical anamorphic flares.",
        mediaUrl: "/creators/digitaldavincis/reels/reel-3.mp4",
        thumbnailUrl: "/creators/digitaldavincis/reels/reel-3.jpg",
        contentType: "Brand Commercials",
        tools: ["Runway", "Topaz Video AI"],
        models: ["Runway Gen-3 Alpha"],
        skills: ["Brand Commercial Direction", "Commercial IP Clearance"],
        workflow: "Runway prompt choreography → Topaz 60fps smoothing",
        formats: ["16:9 Landscape (YouTube/TV)", "4K UHD"],
        commercialUse: true,
      },
      {
        id: "davincis-r4",
        title: "Prism Crystal Optics",
        description: "Luxury eyewear brand visualizer with refractive prism optical physics and chromatic dispersion.",
        mediaUrl: "/creators/digitaldavincis/reels/reel-4.mp4",
        thumbnailUrl: "/creators/digitaldavincis/reels/reel-4.jpg",
        contentType: "Product Visualizers",
        tools: ["Midjourney", "Runway"],
        models: ["Midjourney v6.1", "Runway Gen-3 Alpha"],
        skills: ["Product Hero Animations", "Multi-Format Campaign Delivery"],
        workflow: "Midjourney studio lighting → Runway camera pan",
        formats: ["16:9 Landscape (YouTube/TV)"],
        commercialUse: true,
      },
      {
        id: "davincis-r5",
        title: "Titanium Genesis Watch",
        description: "Macro mechanical reveal of high-end luxury watch movement with brushed titanium surfaces.",
        mediaUrl: "/creators/digitaldavincis/reels/reel-5.mp4",
        thumbnailUrl: "/creators/digitaldavincis/reels/reel-5.jpg",
        contentType: "Brand Commercials",
        tools: ["Flux.1 Dev", "Runway"],
        models: ["Flux.1 Dev", "Runway Gen-3 Alpha"],
        skills: ["Product Hero Animations", "Brand Commercial Direction"],
        workflow: "Flux macro prompts → Runway camera rotation → 4K master",
        formats: ["16:9 Landscape (YouTube/TV)", "4K UHD"],
        commercialUse: true,
      },
    ],
  },
];

export const DEMO_BRAND: BrandProfile = {
  id: "apex-athletics",
  ownerUid: "demo-brand-owner",
  name: "Apex Athletics",
  industry: "Sportswear & Athletic Innovation",
  description: "Next-generation running and lifestyle brand pushing physical and digital boundaries with biometric apparel and shoes.",
  contactEmail: "campaigns@apexathletics.com",
};

export const DEMO_BRIEFS: CreativeBrief[] = [
  {
    id: "brief-sneaker-01",
    brandId: "apex-athletics",
    brandName: "Apex Athletics",
    campaignName: "Futuristic Gen-Z Running Shoe Launch",
    requirements:
      "I need a futuristic 30-second Instagram reel for our new running shoe targeting Gen Z. It should feel energetic and cinematic and we need commercial rights. Consistent runner character in neon cyberpunk cityscape.",
    contentType: "Short-form Video (Reels/TikTok)",
    style: ["Futuristic", "Cinematic", "High-Energy", "Cyberpunk / Neon"],
    platform: "Instagram Reels & TikTok",
    aspectRatio: "9:16 Vertical (Reels/Shorts)",
    targetAudience: "Gen Z Trendsetters & Digital Natives (16-24)",
    deliverables: [
      "1x 30-Second Hero Video Deliverable (9:16)",
      "3x High-Res Still Keyframes",
      "1x Clean Cut for Social Ads",
    ],
    commercialUse: true,
    notes: "Audio sound design must sync with kinetic shoe impacts.",
    status: "Published",
  },
  {
    id: "brief-apparel-02",
    brandId: "apex-athletics",
    brandName: "Apex Athletics",
    campaignName: "Cyberpunk Techwear Apparel Showcase",
    requirements:
      "A cinematic 45-second 16:9 brand film highlighting water-repellent techwear fabric in rainy dystopian urban aesthetic.",
    contentType: "Brand Commercials",
    style: ["Cinematic", "Luxury Aesthetic", "Moody & Atmospheric"],
    platform: "YouTube & Web Video",
    aspectRatio: "16:9 Landscape (YouTube/TV)",
    targetAudience: "Urban Professionals & Tech Enthusiasts (25-40)",
    deliverables: [
      "1x 45-Second 4K Master Video",
      "Cutdowns for YouTube Pre-roll (15s)",
    ],
    commercialUse: true,
    notes: "Requires photorealistic rain particles and dark metallic reflections.",
    status: "Published",
  },
];
